joy_node:
  dev: /dev/input/js0
  deadzone: 0.01
  autorepeat_rate: 50
  coalesce_interval: 0.001

teleop:
  # Default mode - Stop for safety
  default:
    type: topic
    is_default: true
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input
    message_value:
      -
        target: drive.speed
        value: 0.0
      -
        target: drive.steering_angle
        value: 0.035

  # Enable Human control by holding Left Bumper
  human_control:
    type: topic
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: drive.speed
        scale: 0.5                  # joystick will command plus or minus 2 meters / second
        offset: 0.0
      -
        axis: 3
        target: drive.steering_angle
        scale: 0.3                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.035

  # Enable autonomous control by pressing right bumper
  # This switch causes the joy_teleop to stop sending messages to input/teleop
  # And send messages to /dev/null (an unused ROS topic)
  # autonomous_control:
  #   type: topic
  #   message_type: std_msgs/Int8
  #   topic_name: /dev/null
  #   deadman_buttons: [5]
  #   message_value:
  #     -
  #       target: data
  #       value: 0

  autonomous_control:
    type: topic
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input
    deadman_buttons: [5]
    axis_mappings:
      -
        axis: 1
        target: drive.speed
        scale: 0.5                  # joystick will command plus or minus 2 meters / second
        offset: 0.0
      -
        axis: 2
        target: drive.steering_angle
        scale: 0.3                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.035
